// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: honghaier.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Merlincomm {

  /// <summary>Holder for reflection information generated from honghaier.proto</summary>
  public static partial class HonghaierReflection {

    #region Descriptor
    /// <summary>File descriptor for honghaier.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HonghaierReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9ob25naGFpZXIucHJvdG8SCm1lcmxpbmNvbW0iLQoLUmVhZFJlcXVlc3QS",
            "DwoHc3JjTmFtZRgBIAEoCRINCgVyZXFTThgCIAEoAyLUAQoJUmVhZFJlcGx5",
            "Eg8KB3NyY05hbWUYASABKAkSDQoFcmVxU04YAiABKAMSDQoFc3RhdGUYAyAB",
            "KAUSDwoHZXJyQ29kZRgEIAEoBRITCgtyb3RhdGVTcGVlZBgFIAEoAhIMCgRh",
            "bXBzGAYgAygCEg8KB3ZvbHRhZ2UYByADKAISEgoKdGVtcGVyU3RlcBgIIAMo",
            "AhIVCg10ZW1wZXJPbldhZmVyGAkgAygCEhYKDnRlbXBlck9mZldhZmVyGAog",
            "AygCEhAKCHRlbXBlclRjGAsgAygCIoACCgxXcml0ZVJlcXVlc3QSDwoHc3Jj",
            "TmFtZRgBIAEoCRINCgVyZXFTThgCIAEoAxIPCgdjdHJsVmFyGAMgASgFEhAK",
            "CGN0cmxNb2RlGAQgASgFEhEKCXBhcmFtZXRlchgFIAEoBRIRCglzdGFydFRp",
            "bWUYBiABKAESEAoIdGltZVNwYW4YByABKAISEgoKdGVtcFRhcmdldBgIIAMo",
            "AhIPCgdjdXJyZW50GAkgAygCEg8KB3ZvbHRhZ2UYCiADKAISFQoNdGVtcGVy",
            "T25XYWZlchgLIAMoAhIWCg50ZW1wZXJPZmZXYWZlchgMIAMoAhIQCgh0ZW1w",
            "ZXJUYxgNIAMoAiJdCgpXcml0ZVJlcGx5Eg8KB3NyY05hbWUYASABKAkSDQoF",
            "cmVxU04YAiABKAMSDQoFc3RhdGUYAyABKAUSDwoHZXJyQ29kZRgEIAEoBRIP",
            "CgdjdXJyZW50GAggAygCIkoKE0hlYXJ0QmVhdFJlcXVlc3RISFISDwoHc3Jj",
            "TmFtZRgBIAEoCRINCgVyZXFTThgCIAEoAxITCgt0aW1lT3V0U3BhbhgDIAEo",
            "AyJYChFIZWFydEJlYXRSZXBseUhIUhIPCgdzcmNOYW1lGAEgASgJEg0KBXJl",
            "cVNOGAIgASgDEg4KBnJlc3BTThgDIAEoAxITCgt0aW1lT3V0U3BhbhgEIAEo",
            "AzLVAQoNZ1JQQ0hvbmdoYWllchI4CgRSZWFkEhcubWVybGluY29tbS5SZWFk",
            "UmVxdWVzdBoVLm1lcmxpbmNvbW0uUmVhZFJlcGx5IgASOwoFV3JpdGUSGC5t",
            "ZXJsaW5jb21tLldyaXRlUmVxdWVzdBoWLm1lcmxpbmNvbW0uV3JpdGVSZXBs",
            "eSIAEk0KCUhlYXJ0QmVhdBIfLm1lcmxpbmNvbW0uSGVhcnRCZWF0UmVxdWVz",
            "dEhIUhodLm1lcmxpbmNvbW0uSGVhcnRCZWF0UmVwbHlISFIiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Merlincomm.ReadRequest), global::Merlincomm.ReadRequest.Parser, new[]{ "SrcName", "ReqSN" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Merlincomm.ReadReply), global::Merlincomm.ReadReply.Parser, new[]{ "SrcName", "ReqSN", "State", "ErrCode", "RotateSpeed", "Amps", "Voltage", "TemperStep", "TemperOnWafer", "TemperOffWafer", "TemperTc" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Merlincomm.WriteRequest), global::Merlincomm.WriteRequest.Parser, new[]{ "SrcName", "ReqSN", "CtrlVar", "CtrlMode", "Parameter", "StartTime", "TimeSpan", "TempTarget", "Current", "Voltage", "TemperOnWafer", "TemperOffWafer", "TemperTc" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Merlincomm.WriteReply), global::Merlincomm.WriteReply.Parser, new[]{ "SrcName", "ReqSN", "State", "ErrCode", "Current" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Merlincomm.HeartBeatRequestHHR), global::Merlincomm.HeartBeatRequestHHR.Parser, new[]{ "SrcName", "ReqSN", "TimeOutSpan" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Merlincomm.HeartBeatReplyHHR), global::Merlincomm.HeartBeatReplyHHR.Parser, new[]{ "SrcName", "ReqSN", "RespSN", "TimeOutSpan" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ReadRequest : pb::IMessage<ReadRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReadRequest> _parser = new pb::MessageParser<ReadRequest>(() => new ReadRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReadRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Merlincomm.HonghaierReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReadRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReadRequest(ReadRequest other) : this() {
      srcName_ = other.srcName_;
      reqSN_ = other.reqSN_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReadRequest Clone() {
      return new ReadRequest(this);
    }

    /// <summary>Field number for the "srcName" field.</summary>
    public const int SrcNameFieldNumber = 1;
    private string srcName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcName {
      get { return srcName_; }
      set {
        srcName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reqSN" field.</summary>
    public const int ReqSNFieldNumber = 2;
    private long reqSN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReqSN {
      get { return reqSN_; }
      set {
        reqSN_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReadRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReadRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcName != other.SrcName) return false;
      if (ReqSN != other.ReqSN) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcName.Length != 0) hash ^= SrcName.GetHashCode();
      if (ReqSN != 0L) hash ^= ReqSN.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcName);
      }
      if (ReqSN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReqSN);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReadRequest other) {
      if (other == null) {
        return;
      }
      if (other.SrcName.Length != 0) {
        SrcName = other.SrcName;
      }
      if (other.ReqSN != 0L) {
        ReqSN = other.ReqSN;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ReadReply : pb::IMessage<ReadReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReadReply> _parser = new pb::MessageParser<ReadReply>(() => new ReadReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReadReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Merlincomm.HonghaierReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReadReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReadReply(ReadReply other) : this() {
      srcName_ = other.srcName_;
      reqSN_ = other.reqSN_;
      state_ = other.state_;
      errCode_ = other.errCode_;
      rotateSpeed_ = other.rotateSpeed_;
      amps_ = other.amps_.Clone();
      voltage_ = other.voltage_.Clone();
      temperStep_ = other.temperStep_.Clone();
      temperOnWafer_ = other.temperOnWafer_.Clone();
      temperOffWafer_ = other.temperOffWafer_.Clone();
      temperTc_ = other.temperTc_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReadReply Clone() {
      return new ReadReply(this);
    }

    /// <summary>Field number for the "srcName" field.</summary>
    public const int SrcNameFieldNumber = 1;
    private string srcName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcName {
      get { return srcName_; }
      set {
        srcName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reqSN" field.</summary>
    public const int ReqSNFieldNumber = 2;
    private long reqSN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReqSN {
      get { return reqSN_; }
      set {
        reqSN_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private int state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "errCode" field.</summary>
    public const int ErrCodeFieldNumber = 4;
    private int errCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    /// <summary>Field number for the "rotateSpeed" field.</summary>
    public const int RotateSpeedFieldNumber = 5;
    private float rotateSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotateSpeed {
      get { return rotateSpeed_; }
      set {
        rotateSpeed_ = value;
      }
    }

    /// <summary>Field number for the "amps" field.</summary>
    public const int AmpsFieldNumber = 6;
    private static readonly pb::FieldCodec<float> _repeated_amps_codec
        = pb::FieldCodec.ForFloat(50);
    private readonly pbc::RepeatedField<float> amps_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Amps {
      get { return amps_; }
    }

    /// <summary>Field number for the "voltage" field.</summary>
    public const int VoltageFieldNumber = 7;
    private static readonly pb::FieldCodec<float> _repeated_voltage_codec
        = pb::FieldCodec.ForFloat(58);
    private readonly pbc::RepeatedField<float> voltage_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Voltage {
      get { return voltage_; }
    }

    /// <summary>Field number for the "temperStep" field.</summary>
    public const int TemperStepFieldNumber = 8;
    private static readonly pb::FieldCodec<float> _repeated_temperStep_codec
        = pb::FieldCodec.ForFloat(66);
    private readonly pbc::RepeatedField<float> temperStep_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// from wukong
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TemperStep {
      get { return temperStep_; }
    }

    /// <summary>Field number for the "temperOnWafer" field.</summary>
    public const int TemperOnWaferFieldNumber = 9;
    private static readonly pb::FieldCodec<float> _repeated_temperOnWafer_codec
        = pb::FieldCodec.ForFloat(74);
    private readonly pbc::RepeatedField<float> temperOnWafer_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// from wukong
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TemperOnWafer {
      get { return temperOnWafer_; }
    }

    /// <summary>Field number for the "temperOffWafer" field.</summary>
    public const int TemperOffWaferFieldNumber = 10;
    private static readonly pb::FieldCodec<float> _repeated_temperOffWafer_codec
        = pb::FieldCodec.ForFloat(82);
    private readonly pbc::RepeatedField<float> temperOffWafer_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// from wukong
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TemperOffWafer {
      get { return temperOffWafer_; }
    }

    /// <summary>Field number for the "temperTc" field.</summary>
    public const int TemperTcFieldNumber = 11;
    private static readonly pb::FieldCodec<float> _repeated_temperTc_codec
        = pb::FieldCodec.ForFloat(90);
    private readonly pbc::RepeatedField<float> temperTc_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// from plc tc
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TemperTc {
      get { return temperTc_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReadReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReadReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcName != other.SrcName) return false;
      if (ReqSN != other.ReqSN) return false;
      if (State != other.State) return false;
      if (ErrCode != other.ErrCode) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotateSpeed, other.RotateSpeed)) return false;
      if(!amps_.Equals(other.amps_)) return false;
      if(!voltage_.Equals(other.voltage_)) return false;
      if(!temperStep_.Equals(other.temperStep_)) return false;
      if(!temperOnWafer_.Equals(other.temperOnWafer_)) return false;
      if(!temperOffWafer_.Equals(other.temperOffWafer_)) return false;
      if(!temperTc_.Equals(other.temperTc_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcName.Length != 0) hash ^= SrcName.GetHashCode();
      if (ReqSN != 0L) hash ^= ReqSN.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
      if (RotateSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotateSpeed);
      hash ^= amps_.GetHashCode();
      hash ^= voltage_.GetHashCode();
      hash ^= temperStep_.GetHashCode();
      hash ^= temperOnWafer_.GetHashCode();
      hash ^= temperOffWafer_.GetHashCode();
      hash ^= temperTc_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (State != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(State);
      }
      if (ErrCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ErrCode);
      }
      if (RotateSpeed != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(RotateSpeed);
      }
      amps_.WriteTo(output, _repeated_amps_codec);
      voltage_.WriteTo(output, _repeated_voltage_codec);
      temperStep_.WriteTo(output, _repeated_temperStep_codec);
      temperOnWafer_.WriteTo(output, _repeated_temperOnWafer_codec);
      temperOffWafer_.WriteTo(output, _repeated_temperOffWafer_codec);
      temperTc_.WriteTo(output, _repeated_temperTc_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (State != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(State);
      }
      if (ErrCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ErrCode);
      }
      if (RotateSpeed != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(RotateSpeed);
      }
      amps_.WriteTo(ref output, _repeated_amps_codec);
      voltage_.WriteTo(ref output, _repeated_voltage_codec);
      temperStep_.WriteTo(ref output, _repeated_temperStep_codec);
      temperOnWafer_.WriteTo(ref output, _repeated_temperOnWafer_codec);
      temperOffWafer_.WriteTo(ref output, _repeated_temperOffWafer_codec);
      temperTc_.WriteTo(ref output, _repeated_temperTc_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcName);
      }
      if (ReqSN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReqSN);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (ErrCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
      }
      if (RotateSpeed != 0F) {
        size += 1 + 4;
      }
      size += amps_.CalculateSize(_repeated_amps_codec);
      size += voltage_.CalculateSize(_repeated_voltage_codec);
      size += temperStep_.CalculateSize(_repeated_temperStep_codec);
      size += temperOnWafer_.CalculateSize(_repeated_temperOnWafer_codec);
      size += temperOffWafer_.CalculateSize(_repeated_temperOffWafer_codec);
      size += temperTc_.CalculateSize(_repeated_temperTc_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReadReply other) {
      if (other == null) {
        return;
      }
      if (other.SrcName.Length != 0) {
        SrcName = other.SrcName;
      }
      if (other.ReqSN != 0L) {
        ReqSN = other.ReqSN;
      }
      if (other.State != 0) {
        State = other.State;
      }
      if (other.ErrCode != 0) {
        ErrCode = other.ErrCode;
      }
      if (other.RotateSpeed != 0F) {
        RotateSpeed = other.RotateSpeed;
      }
      amps_.Add(other.amps_);
      voltage_.Add(other.voltage_);
      temperStep_.Add(other.temperStep_);
      temperOnWafer_.Add(other.temperOnWafer_);
      temperOffWafer_.Add(other.temperOffWafer_);
      temperTc_.Add(other.temperTc_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            State = input.ReadInt32();
            break;
          }
          case 32: {
            ErrCode = input.ReadInt32();
            break;
          }
          case 45: {
            RotateSpeed = input.ReadFloat();
            break;
          }
          case 50:
          case 53: {
            amps_.AddEntriesFrom(input, _repeated_amps_codec);
            break;
          }
          case 58:
          case 61: {
            voltage_.AddEntriesFrom(input, _repeated_voltage_codec);
            break;
          }
          case 66:
          case 69: {
            temperStep_.AddEntriesFrom(input, _repeated_temperStep_codec);
            break;
          }
          case 74:
          case 77: {
            temperOnWafer_.AddEntriesFrom(input, _repeated_temperOnWafer_codec);
            break;
          }
          case 82:
          case 85: {
            temperOffWafer_.AddEntriesFrom(input, _repeated_temperOffWafer_codec);
            break;
          }
          case 90:
          case 93: {
            temperTc_.AddEntriesFrom(input, _repeated_temperTc_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            State = input.ReadInt32();
            break;
          }
          case 32: {
            ErrCode = input.ReadInt32();
            break;
          }
          case 45: {
            RotateSpeed = input.ReadFloat();
            break;
          }
          case 50:
          case 53: {
            amps_.AddEntriesFrom(ref input, _repeated_amps_codec);
            break;
          }
          case 58:
          case 61: {
            voltage_.AddEntriesFrom(ref input, _repeated_voltage_codec);
            break;
          }
          case 66:
          case 69: {
            temperStep_.AddEntriesFrom(ref input, _repeated_temperStep_codec);
            break;
          }
          case 74:
          case 77: {
            temperOnWafer_.AddEntriesFrom(ref input, _repeated_temperOnWafer_codec);
            break;
          }
          case 82:
          case 85: {
            temperOffWafer_.AddEntriesFrom(ref input, _repeated_temperOffWafer_codec);
            break;
          }
          case 90:
          case 93: {
            temperTc_.AddEntriesFrom(ref input, _repeated_temperTc_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WriteRequest : pb::IMessage<WriteRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WriteRequest> _parser = new pb::MessageParser<WriteRequest>(() => new WriteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WriteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Merlincomm.HonghaierReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WriteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WriteRequest(WriteRequest other) : this() {
      srcName_ = other.srcName_;
      reqSN_ = other.reqSN_;
      ctrlVar_ = other.ctrlVar_;
      ctrlMode_ = other.ctrlMode_;
      parameter_ = other.parameter_;
      startTime_ = other.startTime_;
      timeSpan_ = other.timeSpan_;
      tempTarget_ = other.tempTarget_.Clone();
      current_ = other.current_.Clone();
      voltage_ = other.voltage_.Clone();
      temperOnWafer_ = other.temperOnWafer_.Clone();
      temperOffWafer_ = other.temperOffWafer_.Clone();
      temperTc_ = other.temperTc_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WriteRequest Clone() {
      return new WriteRequest(this);
    }

    /// <summary>Field number for the "srcName" field.</summary>
    public const int SrcNameFieldNumber = 1;
    private string srcName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcName {
      get { return srcName_; }
      set {
        srcName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reqSN" field.</summary>
    public const int ReqSNFieldNumber = 2;
    private long reqSN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReqSN {
      get { return reqSN_; }
      set {
        reqSN_ = value;
      }
    }

    /// <summary>Field number for the "ctrlVar" field.</summary>
    public const int CtrlVarFieldNumber = 3;
    private int ctrlVar_;
    /// <summary>
    ///1:temp[OnWafer]Target  2:temp[OffWafer]Target 3:temp[Susceptor]Target
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CtrlVar {
      get { return ctrlVar_; }
      set {
        ctrlVar_ = value;
      }
    }

    /// <summary>Field number for the "ctrlMode" field.</summary>
    public const int CtrlModeFieldNumber = 4;
    private int ctrlMode_;
    /// <summary>
    ///0:MPC_SPEED  1:MPC_OVERSHOOT 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CtrlMode {
      get { return ctrlMode_; }
      set {
        ctrlMode_ = value;
      }
    }

    /// <summary>Field number for the "parameter" field.</summary>
    public const int ParameterFieldNumber = 5;
    private int parameter_;
    /// <summary>
    ///0:Ramp start from feedback  1:Ramp start from target 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Parameter {
      get { return parameter_; }
      set {
        parameter_ = value;
      }
    }

    /// <summary>Field number for the "startTime" field.</summary>
    public const int StartTimeFieldNumber = 6;
    private double startTime_;
    /// <summary>
    ///second
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "timeSpan" field.</summary>
    public const int TimeSpanFieldNumber = 7;
    private float timeSpan_;
    /// <summary>
    ///second
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TimeSpan {
      get { return timeSpan_; }
      set {
        timeSpan_ = value;
      }
    }

    /// <summary>Field number for the "tempTarget" field.</summary>
    public const int TempTargetFieldNumber = 8;
    private static readonly pb::FieldCodec<float> _repeated_tempTarget_codec
        = pb::FieldCodec.ForFloat(66);
    private readonly pbc::RepeatedField<float> tempTarget_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TempTarget {
      get { return tempTarget_; }
    }

    /// <summary>Field number for the "current" field.</summary>
    public const int CurrentFieldNumber = 9;
    private static readonly pb::FieldCodec<float> _repeated_current_codec
        = pb::FieldCodec.ForFloat(74);
    private readonly pbc::RepeatedField<float> current_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// current feedback from PSU
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Current {
      get { return current_; }
    }

    /// <summary>Field number for the "voltage" field.</summary>
    public const int VoltageFieldNumber = 10;
    private static readonly pb::FieldCodec<float> _repeated_voltage_codec
        = pb::FieldCodec.ForFloat(82);
    private readonly pbc::RepeatedField<float> voltage_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// voltage feedback from PSU
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Voltage {
      get { return voltage_; }
    }

    /// <summary>Field number for the "temperOnWafer" field.</summary>
    public const int TemperOnWaferFieldNumber = 11;
    private static readonly pb::FieldCodec<float> _repeated_temperOnWafer_codec
        = pb::FieldCodec.ForFloat(90);
    private readonly pbc::RepeatedField<float> temperOnWafer_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// from wukong
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TemperOnWafer {
      get { return temperOnWafer_; }
    }

    /// <summary>Field number for the "temperOffWafer" field.</summary>
    public const int TemperOffWaferFieldNumber = 12;
    private static readonly pb::FieldCodec<float> _repeated_temperOffWafer_codec
        = pb::FieldCodec.ForFloat(98);
    private readonly pbc::RepeatedField<float> temperOffWafer_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// from wukong
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TemperOffWafer {
      get { return temperOffWafer_; }
    }

    /// <summary>Field number for the "temperTc" field.</summary>
    public const int TemperTcFieldNumber = 13;
    private static readonly pb::FieldCodec<float> _repeated_temperTc_codec
        = pb::FieldCodec.ForFloat(106);
    private readonly pbc::RepeatedField<float> temperTc_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// from plc tc
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TemperTc {
      get { return temperTc_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WriteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WriteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcName != other.SrcName) return false;
      if (ReqSN != other.ReqSN) return false;
      if (CtrlVar != other.CtrlVar) return false;
      if (CtrlMode != other.CtrlMode) return false;
      if (Parameter != other.Parameter) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StartTime, other.StartTime)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TimeSpan, other.TimeSpan)) return false;
      if(!tempTarget_.Equals(other.tempTarget_)) return false;
      if(!current_.Equals(other.current_)) return false;
      if(!voltage_.Equals(other.voltage_)) return false;
      if(!temperOnWafer_.Equals(other.temperOnWafer_)) return false;
      if(!temperOffWafer_.Equals(other.temperOffWafer_)) return false;
      if(!temperTc_.Equals(other.temperTc_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcName.Length != 0) hash ^= SrcName.GetHashCode();
      if (ReqSN != 0L) hash ^= ReqSN.GetHashCode();
      if (CtrlVar != 0) hash ^= CtrlVar.GetHashCode();
      if (CtrlMode != 0) hash ^= CtrlMode.GetHashCode();
      if (Parameter != 0) hash ^= Parameter.GetHashCode();
      if (StartTime != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StartTime);
      if (TimeSpan != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TimeSpan);
      hash ^= tempTarget_.GetHashCode();
      hash ^= current_.GetHashCode();
      hash ^= voltage_.GetHashCode();
      hash ^= temperOnWafer_.GetHashCode();
      hash ^= temperOffWafer_.GetHashCode();
      hash ^= temperTc_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (CtrlVar != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CtrlVar);
      }
      if (CtrlMode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CtrlMode);
      }
      if (Parameter != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Parameter);
      }
      if (StartTime != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(StartTime);
      }
      if (TimeSpan != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(TimeSpan);
      }
      tempTarget_.WriteTo(output, _repeated_tempTarget_codec);
      current_.WriteTo(output, _repeated_current_codec);
      voltage_.WriteTo(output, _repeated_voltage_codec);
      temperOnWafer_.WriteTo(output, _repeated_temperOnWafer_codec);
      temperOffWafer_.WriteTo(output, _repeated_temperOffWafer_codec);
      temperTc_.WriteTo(output, _repeated_temperTc_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (CtrlVar != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CtrlVar);
      }
      if (CtrlMode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CtrlMode);
      }
      if (Parameter != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Parameter);
      }
      if (StartTime != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(StartTime);
      }
      if (TimeSpan != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(TimeSpan);
      }
      tempTarget_.WriteTo(ref output, _repeated_tempTarget_codec);
      current_.WriteTo(ref output, _repeated_current_codec);
      voltage_.WriteTo(ref output, _repeated_voltage_codec);
      temperOnWafer_.WriteTo(ref output, _repeated_temperOnWafer_codec);
      temperOffWafer_.WriteTo(ref output, _repeated_temperOffWafer_codec);
      temperTc_.WriteTo(ref output, _repeated_temperTc_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcName);
      }
      if (ReqSN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReqSN);
      }
      if (CtrlVar != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CtrlVar);
      }
      if (CtrlMode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CtrlMode);
      }
      if (Parameter != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Parameter);
      }
      if (StartTime != 0D) {
        size += 1 + 8;
      }
      if (TimeSpan != 0F) {
        size += 1 + 4;
      }
      size += tempTarget_.CalculateSize(_repeated_tempTarget_codec);
      size += current_.CalculateSize(_repeated_current_codec);
      size += voltage_.CalculateSize(_repeated_voltage_codec);
      size += temperOnWafer_.CalculateSize(_repeated_temperOnWafer_codec);
      size += temperOffWafer_.CalculateSize(_repeated_temperOffWafer_codec);
      size += temperTc_.CalculateSize(_repeated_temperTc_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WriteRequest other) {
      if (other == null) {
        return;
      }
      if (other.SrcName.Length != 0) {
        SrcName = other.SrcName;
      }
      if (other.ReqSN != 0L) {
        ReqSN = other.ReqSN;
      }
      if (other.CtrlVar != 0) {
        CtrlVar = other.CtrlVar;
      }
      if (other.CtrlMode != 0) {
        CtrlMode = other.CtrlMode;
      }
      if (other.Parameter != 0) {
        Parameter = other.Parameter;
      }
      if (other.StartTime != 0D) {
        StartTime = other.StartTime;
      }
      if (other.TimeSpan != 0F) {
        TimeSpan = other.TimeSpan;
      }
      tempTarget_.Add(other.tempTarget_);
      current_.Add(other.current_);
      voltage_.Add(other.voltage_);
      temperOnWafer_.Add(other.temperOnWafer_);
      temperOffWafer_.Add(other.temperOffWafer_);
      temperTc_.Add(other.temperTc_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            CtrlVar = input.ReadInt32();
            break;
          }
          case 32: {
            CtrlMode = input.ReadInt32();
            break;
          }
          case 40: {
            Parameter = input.ReadInt32();
            break;
          }
          case 49: {
            StartTime = input.ReadDouble();
            break;
          }
          case 61: {
            TimeSpan = input.ReadFloat();
            break;
          }
          case 66:
          case 69: {
            tempTarget_.AddEntriesFrom(input, _repeated_tempTarget_codec);
            break;
          }
          case 74:
          case 77: {
            current_.AddEntriesFrom(input, _repeated_current_codec);
            break;
          }
          case 82:
          case 85: {
            voltage_.AddEntriesFrom(input, _repeated_voltage_codec);
            break;
          }
          case 90:
          case 93: {
            temperOnWafer_.AddEntriesFrom(input, _repeated_temperOnWafer_codec);
            break;
          }
          case 98:
          case 101: {
            temperOffWafer_.AddEntriesFrom(input, _repeated_temperOffWafer_codec);
            break;
          }
          case 106:
          case 109: {
            temperTc_.AddEntriesFrom(input, _repeated_temperTc_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            CtrlVar = input.ReadInt32();
            break;
          }
          case 32: {
            CtrlMode = input.ReadInt32();
            break;
          }
          case 40: {
            Parameter = input.ReadInt32();
            break;
          }
          case 49: {
            StartTime = input.ReadDouble();
            break;
          }
          case 61: {
            TimeSpan = input.ReadFloat();
            break;
          }
          case 66:
          case 69: {
            tempTarget_.AddEntriesFrom(ref input, _repeated_tempTarget_codec);
            break;
          }
          case 74:
          case 77: {
            current_.AddEntriesFrom(ref input, _repeated_current_codec);
            break;
          }
          case 82:
          case 85: {
            voltage_.AddEntriesFrom(ref input, _repeated_voltage_codec);
            break;
          }
          case 90:
          case 93: {
            temperOnWafer_.AddEntriesFrom(ref input, _repeated_temperOnWafer_codec);
            break;
          }
          case 98:
          case 101: {
            temperOffWafer_.AddEntriesFrom(ref input, _repeated_temperOffWafer_codec);
            break;
          }
          case 106:
          case 109: {
            temperTc_.AddEntriesFrom(ref input, _repeated_temperTc_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WriteReply : pb::IMessage<WriteReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WriteReply> _parser = new pb::MessageParser<WriteReply>(() => new WriteReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WriteReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Merlincomm.HonghaierReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WriteReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WriteReply(WriteReply other) : this() {
      srcName_ = other.srcName_;
      reqSN_ = other.reqSN_;
      state_ = other.state_;
      errCode_ = other.errCode_;
      current_ = other.current_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WriteReply Clone() {
      return new WriteReply(this);
    }

    /// <summary>Field number for the "srcName" field.</summary>
    public const int SrcNameFieldNumber = 1;
    private string srcName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcName {
      get { return srcName_; }
      set {
        srcName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reqSN" field.</summary>
    public const int ReqSNFieldNumber = 2;
    private long reqSN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReqSN {
      get { return reqSN_; }
      set {
        reqSN_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private int state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "errCode" field.</summary>
    public const int ErrCodeFieldNumber = 4;
    private int errCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    /// <summary>Field number for the "current" field.</summary>
    public const int CurrentFieldNumber = 8;
    private static readonly pb::FieldCodec<float> _repeated_current_codec
        = pb::FieldCodec.ForFloat(66);
    private readonly pbc::RepeatedField<float> current_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// current to set for PSU
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Current {
      get { return current_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WriteReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WriteReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcName != other.SrcName) return false;
      if (ReqSN != other.ReqSN) return false;
      if (State != other.State) return false;
      if (ErrCode != other.ErrCode) return false;
      if(!current_.Equals(other.current_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcName.Length != 0) hash ^= SrcName.GetHashCode();
      if (ReqSN != 0L) hash ^= ReqSN.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
      hash ^= current_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (State != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(State);
      }
      if (ErrCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ErrCode);
      }
      current_.WriteTo(output, _repeated_current_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (State != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(State);
      }
      if (ErrCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ErrCode);
      }
      current_.WriteTo(ref output, _repeated_current_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcName);
      }
      if (ReqSN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReqSN);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (ErrCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
      }
      size += current_.CalculateSize(_repeated_current_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WriteReply other) {
      if (other == null) {
        return;
      }
      if (other.SrcName.Length != 0) {
        SrcName = other.SrcName;
      }
      if (other.ReqSN != 0L) {
        ReqSN = other.ReqSN;
      }
      if (other.State != 0) {
        State = other.State;
      }
      if (other.ErrCode != 0) {
        ErrCode = other.ErrCode;
      }
      current_.Add(other.current_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            State = input.ReadInt32();
            break;
          }
          case 32: {
            ErrCode = input.ReadInt32();
            break;
          }
          case 66:
          case 69: {
            current_.AddEntriesFrom(input, _repeated_current_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            State = input.ReadInt32();
            break;
          }
          case 32: {
            ErrCode = input.ReadInt32();
            break;
          }
          case 66:
          case 69: {
            current_.AddEntriesFrom(ref input, _repeated_current_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HeartBeatRequestHHR : pb::IMessage<HeartBeatRequestHHR>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HeartBeatRequestHHR> _parser = new pb::MessageParser<HeartBeatRequestHHR>(() => new HeartBeatRequestHHR());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HeartBeatRequestHHR> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Merlincomm.HonghaierReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartBeatRequestHHR() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartBeatRequestHHR(HeartBeatRequestHHR other) : this() {
      srcName_ = other.srcName_;
      reqSN_ = other.reqSN_;
      timeOutSpan_ = other.timeOutSpan_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartBeatRequestHHR Clone() {
      return new HeartBeatRequestHHR(this);
    }

    /// <summary>Field number for the "srcName" field.</summary>
    public const int SrcNameFieldNumber = 1;
    private string srcName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcName {
      get { return srcName_; }
      set {
        srcName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reqSN" field.</summary>
    public const int ReqSNFieldNumber = 2;
    private long reqSN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReqSN {
      get { return reqSN_; }
      set {
        reqSN_ = value;
      }
    }

    /// <summary>Field number for the "timeOutSpan" field.</summary>
    public const int TimeOutSpanFieldNumber = 3;
    private long timeOutSpan_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeOutSpan {
      get { return timeOutSpan_; }
      set {
        timeOutSpan_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HeartBeatRequestHHR);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HeartBeatRequestHHR other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcName != other.SrcName) return false;
      if (ReqSN != other.ReqSN) return false;
      if (TimeOutSpan != other.TimeOutSpan) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcName.Length != 0) hash ^= SrcName.GetHashCode();
      if (ReqSN != 0L) hash ^= ReqSN.GetHashCode();
      if (TimeOutSpan != 0L) hash ^= TimeOutSpan.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (TimeOutSpan != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeOutSpan);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (TimeOutSpan != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeOutSpan);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcName);
      }
      if (ReqSN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReqSN);
      }
      if (TimeOutSpan != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeOutSpan);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HeartBeatRequestHHR other) {
      if (other == null) {
        return;
      }
      if (other.SrcName.Length != 0) {
        SrcName = other.SrcName;
      }
      if (other.ReqSN != 0L) {
        ReqSN = other.ReqSN;
      }
      if (other.TimeOutSpan != 0L) {
        TimeOutSpan = other.TimeOutSpan;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            TimeOutSpan = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            TimeOutSpan = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HeartBeatReplyHHR : pb::IMessage<HeartBeatReplyHHR>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HeartBeatReplyHHR> _parser = new pb::MessageParser<HeartBeatReplyHHR>(() => new HeartBeatReplyHHR());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HeartBeatReplyHHR> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Merlincomm.HonghaierReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartBeatReplyHHR() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartBeatReplyHHR(HeartBeatReplyHHR other) : this() {
      srcName_ = other.srcName_;
      reqSN_ = other.reqSN_;
      respSN_ = other.respSN_;
      timeOutSpan_ = other.timeOutSpan_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartBeatReplyHHR Clone() {
      return new HeartBeatReplyHHR(this);
    }

    /// <summary>Field number for the "srcName" field.</summary>
    public const int SrcNameFieldNumber = 1;
    private string srcName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcName {
      get { return srcName_; }
      set {
        srcName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reqSN" field.</summary>
    public const int ReqSNFieldNumber = 2;
    private long reqSN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReqSN {
      get { return reqSN_; }
      set {
        reqSN_ = value;
      }
    }

    /// <summary>Field number for the "respSN" field.</summary>
    public const int RespSNFieldNumber = 3;
    private long respSN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RespSN {
      get { return respSN_; }
      set {
        respSN_ = value;
      }
    }

    /// <summary>Field number for the "timeOutSpan" field.</summary>
    public const int TimeOutSpanFieldNumber = 4;
    private long timeOutSpan_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeOutSpan {
      get { return timeOutSpan_; }
      set {
        timeOutSpan_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HeartBeatReplyHHR);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HeartBeatReplyHHR other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SrcName != other.SrcName) return false;
      if (ReqSN != other.ReqSN) return false;
      if (RespSN != other.RespSN) return false;
      if (TimeOutSpan != other.TimeOutSpan) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SrcName.Length != 0) hash ^= SrcName.GetHashCode();
      if (ReqSN != 0L) hash ^= ReqSN.GetHashCode();
      if (RespSN != 0L) hash ^= RespSN.GetHashCode();
      if (TimeOutSpan != 0L) hash ^= TimeOutSpan.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (RespSN != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RespSN);
      }
      if (TimeOutSpan != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TimeOutSpan);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SrcName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SrcName);
      }
      if (ReqSN != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ReqSN);
      }
      if (RespSN != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RespSN);
      }
      if (TimeOutSpan != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TimeOutSpan);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SrcName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcName);
      }
      if (ReqSN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReqSN);
      }
      if (RespSN != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RespSN);
      }
      if (TimeOutSpan != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeOutSpan);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HeartBeatReplyHHR other) {
      if (other == null) {
        return;
      }
      if (other.SrcName.Length != 0) {
        SrcName = other.SrcName;
      }
      if (other.ReqSN != 0L) {
        ReqSN = other.ReqSN;
      }
      if (other.RespSN != 0L) {
        RespSN = other.RespSN;
      }
      if (other.TimeOutSpan != 0L) {
        TimeOutSpan = other.TimeOutSpan;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            RespSN = input.ReadInt64();
            break;
          }
          case 32: {
            TimeOutSpan = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SrcName = input.ReadString();
            break;
          }
          case 16: {
            ReqSN = input.ReadInt64();
            break;
          }
          case 24: {
            RespSN = input.ReadInt64();
            break;
          }
          case 32: {
            TimeOutSpan = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
